import './globals.css';
import 'bootstrap/dist/css/bootstrap.css'
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import ImportBsJS from "@/components/importBsJS";

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'My BCBS Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode; }) {
  return (
    <html lang="en">
      <ImportBsJS />
      <body className={inter.className}>{children}</body>
    </html>
  );
}
